version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classroom
    ports:
      - "3305:3306"
